###
POST http://localhost:8080/api/category
Content-Type: application/json

{
  "name": "Category 9",
  "active": true
}

###
PUT http://localhost:8080/api/category/6
Content-Type: application/json

{
  "name": "Category 6",
  "active": true,
  "categoryId": 1
}

###
# ?page=1&size=2
GET http://localhost:8080/api/category

###
GET http://localhost:8080/api/category/5

###
DELETE http://localhost:8080/api/category/5


