###
POST http://localhost:8080/api/measurement
Content-Type: application/json

{
  "name": "Kilogram"
}

###
GET http://localhost:8080/api/measurement

###
GET http://localhost:8080/api/measurement/{{id}}


