spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lesson2
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  data:
    rest:
      base-path: api